name: HTML5 Build CI
on: [workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install flixel 4.11.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.11.0 --quiet
      - name: Compile
        run: haxelib run lime build html5 -final
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: html5Build
          path: export/release/html5/bin
      - name: Publish Artifact (Only JS)
        uses: actions/upload-artifact@main
        with:
          name: html5OnlyJS
          path: 'export/release/html5/bin/*.js*'
