name: Windows Build CI (Transfer.sh)

on: [workflow_dispatch]

jobs:
  build:
    name: Windows
    runs-on: windows-${{ matrix.version }}
    strategy:
      matrix:
        arch: [32, 64]
        build: [release]
        version: [2019, 2022]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.11.0.git
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
      - name: Compile
        run: haxelib run lime build windows -${{ matrix.arch }} -${{ matrix.build }} -D no-compilation -D macro-times -D analyzer-optimize
      - name: Publish To transfer.sh
        shell: pwsh
        run: |
          cd export/${{ matrix.build }}/windows/bin
          Compress-Archive -Path ./* -DestinationPath stevgotleaked-${{ matrix.build }}-${{ matrix.arch }}.zip
          curl.exe --upload-file stevgotleaked-${{ matrix.build }}-${{ matrix.arch }}.zip https://transfer.sh/stevgotleaked-${{ matrix.build }}-${{ matrix.arch }}.zip
